version: '3'

networks:
  gitlab:
    driver: bridge

secrets:
  traefik.certificate:
    file: ./secrets/gitlab-test.lab.lan-crt.pem
  traefik.key:
    file: ./secrets/gitlab-test.lab.lan-key.pem

services:
  git:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab-test.lab.lan'
    container_name: gitlab-ce
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab-test.lab.lan'
        letsencrypt['enabled'] = false
        nginx['listen_https'] = false
        nginx['listen_port'] = 80
        # Add any other gitlab.rb configuration here, each on its own line
   # ports:
      #- '80:80'
      #- '443:443'
      #- '22:22'
    volumes:
      - ./config:/etc/gitlab'
      - ./logs:/var/log/gitlab'
      - ./data:/var/opt/gitlab'
    shm_size: '256m'
    networks:
      - gitlab
    
    labels:
    # permet a traefik d'avoir des instructions pour ce service
      - "traefik.enable=true"
      - "traefik.http.routers.git.rule=Host(`gitlab-test.lab.lan`)"
      - "traefik.http.routers.git.service=git"
      - "traefik.http.routers.git.entrypoints=https"
      - "traefik.http.services.git.loadbalancer.server.port=80"
      - "traefik.docker.network=gitlab"


  # Image Traefik officielle: https://hub.docker.com/_/traefik
  traefik:
    image: traefik:2.10.5
    command:
      # decommenter pour acceder a la web UI traefik
      #- --api.insecure=true
      # dossier de configurations statique
      - --providers.file.directory=/config
      # indique d'ecouter docker
      - --providers.docker
      # points d'entree
      - --entryPoints.web.address=:80
      - --entryPoints.https.address=:443
      - --entrypoints.https.http.tls=true
    networks:
      - gitlab
    ports:
      # ports d'ecoute du proxy
      - 443:443/tcp
      # Web UI (utiliser avec --api.insecure=true)
      #- 8080:8080/tcp
    volumes:
      # pour que trafic soit au courant des changements dans Docker
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/config:ro
    secrets:
      - source: traefik.certificate
        target: /certs/gitlab-test.lab.lan-crt.pem
      - source: traefik.key
        target: /certs/gitlab-test.lab.lan-key.pem

    #gitlab-runner:
    #image: gitlab/gitlab-runner:alpine
    #container_name: gitlab-runner    
    #restart: always
    #depends_on:
    #  - git
    #volumes:
    #  - /var/run/docker.sock:/var/run/docker.sock
    #  - ./gitlab-runner:/etc/gitlab-runner'
    #networks:
    #  - gitlab

