services:
  git:
    image: 'gitlab/gitlab-ce:17.1.0-ce.0'
    restart: always
    hostname: 'gitlab-test.lab.lan'
    container_name: gitlab-ce
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab-test.lab.lan'
        letsencrypt['enabled'] = false
        nginx['listen_https'] = false
        nginx['listen_port'] = 80
        gitlab_rails['ldap_enabled'] = true
        gitlab_rails['ldap_servers'] = {
        'main' => {
          'label' => 'LAB AD',
          'hosts' => [['srvad1.lab.lan', 636], ['srvad2.lab.lan', 636]],
          'port' => 636,
          'uid' => 'sAMAccountName',
          'encryption' => 'simple_tls',
          'verify_certificates' => true,
          'timeout' => 10,
          'bind_dn' => 'CN=ro_gitlab,OU=SERVICES,OU=ACCOUNTS,OU=LAB,DC=lab,DC=lan',
          'password' => 'strong_pass',
          'active_directory' => true,
          'base' => 'DC=lab,DC=lan',
          'block_auto_created_users' => false,
          'allow_username_or_email_login' => true,
          'lowercase_usernames' => true,
          'user_filter' => '(&(objectClass=user)(memberOf:1.2.840.113556.1.4.1941:=CN=gitlab_users,OU=GROUPS,OU=LAB,DC=lab,DC=lan))',
          'tls_options' => {
              'ca_file' => '/etc/gitlab/trusted-certs/CA-cert.pem',
              'ssl_version' => 'TLSv1_2'
            }
           }
         }
          
        # Add any other gitlab.rb configuration here, each on its own line
    volumes:
      - ./config:/etc/gitlab
      - ./config/trusted-certs/ACR-proxy.pem:/etc/gitlab/trusted-certs/CA-certs.pem
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    shm_size: '8192m'
    networks:
      - traefik-global_traefiknet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.git.rule=Host(`gitlab-test.lab.lan`)"
      - "traefik.http.routers.git.entrypoints=websecure"
      - "traefik.http.routers.git.tls=true"
      - "traefik.http.services.git.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik-global_traefiknet"


    #gitlab-runner:
    #image: gitlab/gitlab-runner:alpine
    #container_name: gitlab-runner    
    #restart: always
    #depends_on:
    #  - git
    #volumes:
    #  - /var/run/docker.sock:/var/run/docker.sock
    #  - ./gitlab-runner:/etc/gitlab-runner'
    #networks:
    #  - gitlab

networks:
  traefik-global_traefiknet:
    external: true
